import "./globals.css";
import NavBar from '../components/NavBar';
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-gray-800 to-gray-950" >
        <header>
          <NavBar/>
        </header>
        <main style={{ flex: '1 0 auto', marginLeft: '20px', marginRight: '20px' }}>
          {children}
        </main>
        <footer style={{ marginTop: 'auto' }}>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
